version: 2

sources:
  - name: public
    database: dbt_db
    schema: public
    description: "Путь к таблице public products"
    tables:
      - name: products
        description: "Таблица с продуктами"
